/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_redwoods_cis18_sectools_PingDecorator */

#ifndef _Included_edu_redwoods_cis18_sectools_PingDecorator
#define _Included_edu_redwoods_cis18_sectools_PingDecorator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_redwoods_cis18_sectools_PingDecorator
 * Method:    pingHost
 * Signature: (Ljava/lang/String;[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_edu_redwoods_cis18_sectools_PingDecorator_pingHost
  (JNIEnv *, jobject, jstring, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
